repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Cleanup trailing whitespaces
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        name: Check '*.sh' files
        files: ^(.*)\.sh$
        exclude: \.venv*$
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.7.0-1
    hooks:
      - id: shfmt
        name: Format '*.sh' files
        files: ^(.*)\.sh$
        exclude: \.venv*$
        args: [-i, "2", -w]
