version: '3'

services:
  ansible-control:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-Debian-11
    image: ansible_client_debian
    container_name: ansible-control
    hostname: control.ansible
    environment:
      - 'TZ=Europe/Berlin'
    volumes:
      - ./ansible-files:/root/ansible:rw
      - ./entrypoint/scripts:/entrypoint/scripts:ro
      - ./ssh-keys/server:/root/.ssh:rw
    networks:
      - ansible

  ansible-client-debian:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-Debian-11
    image: ansible_client_debian
    container_name: ansible-client-debian
    hostname: debian.client.ansible
    depends_on:
      - ansible-control
    environment:
      - 'TZ=Europe/Berlin'
    volumes:
      - ./ssh-keys/server/authorized_keys:/root/.ssh/authorized_keys:ro
    networks:
      - ansible

  ansible-client-ubuntu:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-Ubuntu-22.04
    image: ansible_client_ubuntu
    container_name: ansible-client-ubuntu
    hostname: ubuntu.client.ansible
    depends_on:
      - ansible-control
    environment:
      - 'TZ=Europe/Berlin'
    volumes:
      - ./ssh-keys/server/authorized_keys:/root/.ssh/authorized_keys:ro
    networks:
      - ansible

  ansible-client-alma:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-Alma-8
    image: ansible_client_alma
    container_name: ansible-client-alma
    hostname: alma.client.ansible
    depends_on:
      - ansible-control
    environment:
      - 'TZ=Europe/Berlin'
    volumes:
      - ./ssh-keys/server/authorized_keys:/root/.ssh/authorized_keys:ro
    networks:
      - ansible

networks:
  ansible:
