---
# ansible-galaxy collection install -r requirements.yml
collections:
  - ansible.posix
  - community.general

# ansible-galaxy role install -r requirements.yml
roles:
  - name: user-management
    src: https://github.com/Xenion1987/user-management
    version: main
