---
all:
  children:
    clients:
      vars:
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_connection: ssh
        ansible_ssh_common_args: "-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        ansible_ssh_transfer_method: scp
        ansible_ssh_user: root
      children:
        deb_based:
          children:
            debian:
              hosts:
                ansible-client-debian:
            ubuntu:
              hosts:
                ansible-client-ubuntu:
        rpm_based:
          children:
            almalinux:
              hosts:
                ansible-client-alma:
            suse:
              hosts:
                ansible-client-suse:
