---
# tasks file for roles/user_management

- name: Ensure 'sudo' is installed
  ansible.builtin.package:
    name: sudo
    state: present
  when: user_management_default_sudo_mode == "sudo"

- name: "Ensure custom primary group is created"
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ user_management_custom_primary_group | default('[]') }}"

- name: Ensure custom secondary groups are created
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  loop: "{{ user_management_custom_secondary_groups | default('[]') }}"

- name: Ensure home directory exists
  ansible.builtin.file:
    path: "{{ user_management_default_home_root }}"
    state: directory
    mode: "0755"

- name: Include tasks 'manage_user'
  ansible.builtin.include_tasks:
    file: manage_user.yml
  loop: "{{ user_management_users }}"

- name: Include tasks 'manage_ssh_pubkeys'
  ansible.builtin.include_tasks:
    file: manage_ssh_pubkeys.yml
  loop: "{{ user_management_users }}"
