---
- name: Manage authorized key for {{ item.name }}
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', item.name + '.pubkey', errors='ignore') | default('') }}"
    exclusive: true
    key_options: "{{ 'from=' + (user_management_global_ssh_from + (',' + item.custom_ssh_from if item.custom_ssh_from | default('') else '')) if user_management_global_ssh_from or (item.custom_ssh_from | default('')) }}"
  when: item.state == 'present'
