---
- name: Manage authorized key for {{ item.name }} # noqa jinja[spacing]
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key_options: |-
      {%- set from_options_global = user_management_default_ssh_from | default('') -%}
      {%- set from_options_custom_item = item.custom_ssh_from | default('') -%}
      {%- set from_options_custom_host = custom_ssh_from | default('') -%}
      {%- set from_options_custom = from_options_custom_item + ',' + from_options_custom_host if from_options_custom_item and from_options_custom_host else from_options_custom_item if from_options_custom_item else from_options_custom_host -%}
      {%- set from_options = from_options_global + (',' + from_options_custom) if from_options_global != '*' else from_options_custom -%}
      from="{% if from_options %}{{ from_options | trim }}{% else %}*{% endif %}"
    key: "{{ lookup('file', item.name + '.pubkey', errors='ignore') | default('') }}"
    exclusive: true
  when: item.state == 'present'
