---
# tasks file for roles/ufw
- name: Configure UFW service state
  tags:
    - ufw
  block:
    - name: Configuring service
      ansible.builtin.template:
        src: "{{ ufw_config_file | basename }}.j2"
        dest: "{{ ufw_config_file }}"
        mode: "0644"
      notify: reload ufw
      when: ufw_manage_config | bool
