---
# tasks file for roles/ufw
- name: Configure UFW service state
  tags:
    - ufw
  block:
    - name: Configure UFW service state
      community.general.ufw:
        state: "{{ 'enabled' if ufw_enabled else 'disabled' }}"
