---
services:
  ansible-client-debian:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile-Debian-12-client
      args:
        TZ: Europe/Berlin
    image: ansible-client-debian
    hostname: debian.client.ansible
    environment:
      - "TZ=Europe/Berlin"
    networks:
      - ansible-playground

  # ansible-client-ubuntu:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfiles/Dockerfile-Ubuntu-2204
  #     args:
  #       TZ: Europe/Berlin
  #   image: ansible-client-ubuntu
  #   hostname: ubuntu.client.ansible
  #   environment:
  #     - "TZ=Europe/Berlin"
  #   networks:
  #     - ansible-playground

  ansible-client-alma:
    build:
      context: .
      dockerfile: ./Dockerfiles/Dockerfile-Alma-8
      args:
        TZ: Europe/Berlin
    image: ansible-client-alma
    hostname: alma.client.ansible
    environment:
      - "TZ=Europe/Berlin"
    networks:
      - ansible-playground

  # ansible-client-suse:
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfiles/Dockerfile-OpenSUSE-Leap-15
  #     args:
  #       TZ: Europe/Berlin
  #   image: ansible-client-suse
  #   hostname: suse.client.ansible
  #   environment:
  #     - "TZ=Europe/Berlin"
  #   networks:
  #     - ansible-playground

networks:
  ansible-playground:
