---
- name: Play for setting up Uncomplicated FireWall
  hosts: all
  gather_facts: true

  tasks:
    - name: Skip if host is a container
      ansible.builtin.command:
        cmd: pgrep -f /sbin/init
      changed_when: false
      failed_when: false
      register: get_pid_init
    - name: Include role 'ufw'
      ansible.builtin.include_role:
        name: ufw
      when: get_pid_init.stdout == "1"
